# Header
menu:
  Home: /
  Blog: /blog
  Archives: /blog/archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-53479775-2
favicon: /favicon.png
